### ISSUE TITLE
Authentication Issue in Modules

### ISSUE THREAD

**Issue by jamalnasir** [sboo/multiauth#10]
Hi,

I am getting the following error when i implement the multiauth in modules (with different namespaces). Otherwise, it works fine. Can you please tell me what am i missing?

The error occurs when I un-comment the following lines in routes file.
```php
Route::controllers([
        'auth' => 'Auth\AuthController',
        'password' => 'Auth\PasswordController',
    ]);
```

![screenshot_1](https://cloud.githubusercontent.com/assets/1989782/7452978/c9c000a6-f27d-11e4-9e06-2158bf97d9ca.jpg)

**Comment by sboo** [comment]
in your Middleware\Authenticate class there's still the Guard injection in the __construct. As stated in the documentation, those don't work
