### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by raulp** [sboo/multiauth#11]
Hey guys
With the release of 5.1 coming soon, i assume this package will just work with no problems, right ?
I don't see anything major in 5.1 that will break, but just wanna double check

Also, i see that in the requirements you've set laravel 5.0. Guess those will be bumped up when 5.1 goes live ?

Thanks for the package. Used the one in 4.2 with no issues, great stuff !

**Comment by sboo** [comment]
I will have to look into it and test it, but as long as nothing major breaking is introduced I'll try and make it work asap

**Comment by raulp** [comment]
Thanks for your hard work

**Comment by marcellorg** [comment]
It is scheduled to release for 5.1?
thanks for the package, very good.

**Comment by sboo** [comment]
I'm on holidays right now, I'll update early next week
