### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by tmthn** [sboo/multiauth#13]
Hi,
i am a little bit confused about the line with the email. What is client.emails.password doing in this context?

```
'client' => [
     'driver' => 'database',
     'table' => 'clients',
     'email' => 'client.emails.password',
]
```

**Comment by sboo** [comment]
HI,

That's optional and is regarding the password recovery email blade template (view).
If you don't set it then it will use the default that is further down in the same config file.

**Comment by sboo** [comment]
Just to elaborate: in many cases it's useful to have different emails sent out to the different types of accounts. And if you use the built in password recovery, this will be used.
