### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by marcellorg** [sboo/multiauth#14]
Will have upgrade to laravel 5.1, released today?

**Comment by sboo** [comment]
I'm on holidays right now, I'll update early next week

**Comment by devmark** [comment]
thanks

**Comment by subdesign** [comment]
Waiting for that :)

**Comment by marcellorg** [comment]
Waiting. thank you

**Comment by JayBizzle** [comment]
:+1:

**Comment by akhedrane** [comment]
any news on this issue?

**Comment by sboo** [comment]
There are some issues I need to resolve first before it is compatible again. Laravel changed a few things in the default AuthController handling

**Comment by marcellorg** [comment]
I did a fork just changed the composer.json and everything is normal ..
https://github.com/marcellorg/multiauth

**Comment by subdesign** [comment]
@marcellorg and u sure it's 100% working?

**Comment by sboo** [comment]
The code itself works, but not with the standard AuthController and Traits.

\Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers, more specifically Illuminate\Foundation\Auth\AuthenticatesUsers::postLogin() does not work.

I will update composer.json but be aware that you need to write your own Auth routine

**Comment by marcellorg** [comment]
@subdesign Yes, 100% working.

**Comment by sboo** [comment]
I updated composer.json and it will install with 5.1 now. However, read the 5.1 warning
