### ISSUE TITLE
Composer update issue 5.1

### ISSUE THREAD

**Issue by paulfry** [sboo/multiauth#15]
Hello,

Firstly, awesome package, it's GREAT.

I'm having issues with upgrading to 5.1:

- Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - sboo/multiauth v4.0.7 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.33], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - sboo/multiauth v4.0.7 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.33], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].

Any suggestions? 

Kind Regards

**Comment by sboo** [comment]
You need to upgrade multiauth to 4.0.9, that's the version that is compatible with 5.1. Also, be aware: The default AuthController and PasswordController of 5.1 will not work (as stated in the latest readme.md) I am working on Traits and Controllers that can be used instead, but as for now, you'll have to write them yourself.

Cheers,
Ramon
