### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by tavicu** [sboo/multiauth#16]
Hello,

I've read all closed issues but i still can't figure out how to make multiauth works in 5.1

I did eveything like here: https://gist.github.com/sboo/10943f39429b001dd9d0 but i get this error:

BindingResolutionException in Container.php line 744:
Target [Illuminate\Contracts\Auth\Registrar] is not instantiable.

Thanks,
Octavian Ruda

**Comment by sboo** [comment]
Hi Octavian, 

5.1 changed quite a few things in their default controllers and traits that are not directly compatible with the example code. 

Registrar doesn't exist anymore. I'm working on traits and usable controllers, but I don't have them ready just yet. It's not much work and easy to figure out for yourself, I just didn't have time yet. 

I'll keep you posted. 

Cheers,
Ramon

**Comment by tavicu** [comment]
Hey,

Oh, i thought that was for 5.1 :)

Thank you for this awesome package. Waiting for the update :)

**Comment by youndivian** [comment]
I am using it on 5.1 but it I am not getting that error. Is this solved?

**Comment by sboo** [comment]
It might be that there was an update again from Laravel that reenabled that. I haven't checked yet.

**Comment by dennisoderwald** [comment]
+1

**Comment by phelippe** [comment]
+1

**Comment by sboo** [comment]
Please check https://github.com/ollieread/multiauth for further updates for Laravel 5.1. Basically all the issues should be resolved there.
