### ISSUE TITLE
Two tables, user same id

### ISSUE THREAD

**Issue by isomis** [sboo/multiauth#21]
I have multiauth working. Only there is one problem. If you have a table admin and a table user with this config:

    */
    //'table' => 'users',
    'multi' => [
        'admin' => [
            'driver' => 'eloquent',
            'model' => 'App\User',
        ],
        'client' => [
            'driver' => 'eloquent',
            'model' => 'App\Client',
        ]
    ],

And you login as client with user id 1 and you go to admin. You are also the admin user, because that user has also user id 1.

**Comment by sboo** [comment]
Then there's something wrong with your implementation. I have this setup working and this most definitely not an issue. Double check that your models use a different table and also that you use Auth::admin() and Auth::user() correctly in the right context.

**Comment by isomis** [comment]
I fixed the problem. Need to use the correct logout: Auth::user().
