### ISSUE TITLE
problem with login as admin

### ISSUE THREAD

**Issue by mortenko** [sboo/multiauth#23]
Hi Im using multiauth for login as user and admin. User can log on without any problems but It doesnt work for admin. I created table admin and wrote manually the name (admin) and password (admin) into table admin. 
This code doesnt execute:
if(Auth::administrator()->attempt($credentials,$request->has('remember'))) {
......

}
   

this is my auth.php
return [    
'multi' => [

        'client' => [
            'driver' => 'eloquent',
            'table' => 'registration',
            'model' => App\Registration::class,
          /*  'email' => 'client.emails.password',*/
         ],
        'administrator' => [
            'driver' => 'eloquent',
            'table' => 'admin',
            'model' => App\Admin::class,
        ],
        ],

];
    'multi' => [

        'client' => [
            'driver' => 'eloquent',
            'table' => 'registration',
            'model' => App\Registration::class,
          /*  'email' => 'client.emails.password',*/
         ],
        'administrator' => [
            'driver' => 'eloquent',
            'table' => 'admin',
            'model' => App\Admin::class,
        ],
        ],
];
If admin wants to log on , I need only check If the record in database can fetch with admin input . 
Im using laravel 5.1

**Comment by mortenko** [comment]
I solved problem.

**Comment by sboo** [comment]
Good to hear
