### ISSUE TITLE
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

### ISSUE THREAD

**Issue by rajanrawal** [sboo/multiauth#29]
Laravel 5.1.16

php artisan clear compiled

composer updated 

composer dump-autoload -o

All tried but getting

App crashing. Throwing error:
```
BindingResolutionException in Container.php line 744: 
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.
```

**Comment by sboo** [comment]
Did you read the documentation and the gist? there is also a disclaimer regarding laravel 5.1

**Comment by Cavaleri** [comment]
I'm not completely sure, but I think this is due to this commit to the Laravel Framework?
https://github.com/laravel/laravel/commit/7d4b5d75efb7ec201a0eb9486963cb7bd91e323a

I am still not sure how to fix this issue - I'm facing the same problem.

**Comment by sboo** [comment]
Hmm I'm worried that due to all the changes in 5.1, multiauth needs a bigger rewrite to make it usable. Right now, I simply don't have the spare time to dive into it :(

**Comment by rajanrawal** [comment]
@sboo Sorry, but there is whole lot a big community is dependent you. Since laravel has moved from 4.2 and ollieread/multiauth is old, we've become help less. Only solution to go ahead is that old sessiob based login, Should the session based login ok? Just asking.

**Comment by dennisoderwald** [comment]
+1

**Comment by lucas-macedo** [comment]
I have the same problem... 
Whats the solution?

**Comment by sboo** [comment]
I'll try and make some time this weekend. I wouldn't mind if any of you would dive in too, it's not that complicated, just needs some clever thinking

**Comment by rajanrawal** [comment]
@sboo this would be a great opportunity and I would love to do. If you can provide some guidance, I can do that.

**Comment by esalazarv** [comment]
I added support for laravel v5.1.11 https://github.com/esalazarv/multiauth

**Comment by Sarav-S** [comment]
For people who are using Laravel 5.1+ check this https://github.com/Sarav-S/Laravel-Multiauth

**Comment by sboo** [comment]
ollieread/multiauth is up to date with laravel 5.1
