### ISSUE TITLE
i am getting this error while configuring package 

### ISSUE THREAD

**Issue by vachanesh** [sboo/multiauth#39]
**Target [Illuminate\Contracts\Auth\Access\Gate] is not [instantiable.**] in  in Container.php line 752

Please let me know about this issue i am stuck in this......

**Comment by sboo** [comment]
This issue is explained in the readme + https://gist.github.com/sboo/10943f39429b001dd9d0. Furthermore, this version is only really compatible with 5.0. from 5.2 onward, the same functionality is basically built into Laravel, so I saw no point in working on this.
