### ISSUE TITLE
Remember me doesn't work

### ISSUE THREAD

**Issue by koray-mobven** [sboo/multiauth#5]
Hello,
I add a boolean to attempt method just like original one but Auth::user()->viaRemember() returns nothing. What could be problem?

Code:

Auth::user()->attempt(array(
			'gsm'     => \Request::input('gsm'),
			'password'  => \Request::input('password'),
		), TRUE);

Note: login works normally.

**Comment by sboo** [comment]
Sorry I haven't come back to this yet. I'll have to have a look, but it seems to work here. Can you check if the cookie is set correctly upon successful login? Should be remember_type_token, for example remember_user_123456789abcde

**Comment by paulfry** [comment]
Hello,

I'm struggling with the password reset.....I get the following error:

Call to undefined method Ollieread\Multiauth\Passwords\PasswordBroker::remind()

I'm attempting the following as per the original instructions: https://github.com/ollieread/multiauth

Password::admin()->remind( Input::only('email') , function( $message ) {
            $message->subject( 'Password reminder' );
})

Thanks in-advance
