### ISSUE TITLE
Some confusions to be cleared

### ISSUE THREAD

**Issue by jamalnasir** [sboo/multiauth#8]
I am new to Laravel and I have the following confusions regarding your package.

* You did not change the path in the form action (of default registration) which will create the default user. For which I created a separate registration form in client's views. Where I am storing and authenticating a client and the same goes for admin. Am I doing it the wrong way?
* In the config\auth.php you defined two auths with different drivers. Why different drivers? What if both have eloquent driver?

**Comment by sboo** [comment]
If you look at the code on how it handles the default, it uses the AuthController and Authenticate/RedirectIfAuthenticated Middleware.

In my project, I created a separate AuthController and Middleware for the different types of accounts and therefore also separate routes.

Does that clear it up for you?

**Comment by jamalnasir** [comment]
That is crystal clear now. Thanks a lot for your time. :)

On Thu, Apr 16, 2015 at 2:38 PM, Ramon Ackermann <notifications@github.com>
wrote:

> If you look at the code on how it handles the default, it uses the
> AuthController and Authenticate/RedirectIfAuthenticated Middleware.
>
> In my project, I created a separate AuthController and Middleware for the
> different types of accounts and therefore also separate routes.
>
> Does that clear it up for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sboo/multiauth/issues/8#issuecomment-93692783>.
>



-- 
Regards...

Jamal Abdul Nasir
