### ISSUE TITLE
Password Reminder

### ISSUE THREAD

**Issue by paulfry** [sboo/multiauth#9]
Hello,

I'm struggling with the password reset.....I get the following error:

Call to undefined method Ollieread\Multiauth\Passwords\PasswordBroker::remind()

I'm attempting the following as per the original instructions: https://github.com/ollieread/multiauth

Password::admin()->remind( Input::only('email') , function( $message ) {
$message->subject( 'Password reminder' );
})

Thanks in-advance

**Comment by sboo** [comment]
Ollieread's version is for Laravel 4 and uses different methods.

This is the correct method:

```
Password::admin()->sendResetLink(Input::only('email'), function($message )
{
    $message->subject( 'Password reminder' );
});
```
